steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kunal-ica1/my-backend', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kunal-ica1/my-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kunal-ica1/my-frontend', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kunal-ica1/my-frontend']
  - name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="project_id=kunal-ica1" -var="region=us-central1" -var="zone=us-central1-a" -var="cluster_name=my-gke-cluster" -var="frontend_image=gcr.io/kunal-ica1/my-frontend:latest" -var="backend_image=gcr.io/kunal-ica1/my-backend:latest" -var="pg_host=34.133.181.58" -var="pg_database=postgres" -var="pg_user=postgres" -var="pg_password=Kunal"
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'backend/backend-deployment.yaml'
      - '-n'
      - 'example-namespace'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'backend/backend-service.yaml'
      - '-n'
      - 'example-namespace'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'frontend/frontend-deployment.yaml'
      - '-n'
      - 'example-namespace'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'frontend/frontend-service.yaml'
      - '-n'
      - 'example-namespace'

images:
  - 'gcr.io/kunal-ica1/my-backend'
  - 'gcr.io/kunal-ica1/my-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
