steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kunal-ica1/my-backend', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kunal-ica1/my-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kunal-ica1/my-frontend', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kunal-ica1/my-frontend']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'backend/backend-deployment.yaml'
      - '-n'
      - 'example-namespace'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'backend/backend-service.yaml'
      - '-n'
      - 'example-namespace'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'frontend/frontend-deployment.yaml'
      - '-n'
      - 'example-namespace'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'frontend/frontend-service.yaml'
      - '-n'
      - 'example-namespace'

images:
  - 'gcr.io/kunal-ica1/my-backend'
  - 'gcr.io/kunal-ica1/my-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
